### ISSUE TITLE
Document empty BUILD file

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-bazel#8]
There is need for a judgment call if even empty BUILD files need to be documented. The primary use case is file exposure to the build system.

**Comment by danwos** [comment]
I have not understood the requirement completely, but let me try to a first spec:

A new config-value for conf.py gets created: bazel_support_empty_buildfiles. True/False (Default True)

If this option is set to False, folder with an empty BUILD file will not get documented.
If True the folder will be treated as a normal bazel package.

**Comment by apekter** [comment]
> If this option is set to False, folder with an empty BUILD file will not get documented.

This is not a good idea. 
The purpose of an empty BUILD file in a folder with .bzl files is to make bazel aware of the .bzl files, therefore this can lead to a disaster. 
In all the cases the BUILD file has to be handled because an empty BUILD file means that there is no targets in that package, however there could be rules that still need to be documented as the usage of the rules can be located elsewhere in the project.

**Comment by danwos** [comment]
Still don't get it, sorry...
So what should sphinx-bazel do differently, if a BUILD file has content or not?

Currently the containing folder is detected as package and gets documented (name and maybe docstring, if BUILD has content).
That's it. Nothing more is done.

So we only can decide, if this package-documentation shall be hidden, if BUILD is empty.
But .bzl files inside this folder get still documented.
It that your use case?

**Comment by apekter** [comment]
This issue could be combined with the https://github.com/useblocks/sphinx-bazel/issues/7 issue as it will get resolved automatically if sphinx-bazel generates the documentation from the standpoint of a target instead of the file structure.

**Comment by danwos** [comment]
Discussion is ongoing in #7...
Close this issue.
